// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEN5yJHeLj0km92JXecC3YlD7IMwKU7VE',
    appId: '1:319907892766:web:076a54f61f93342207680f',
    messagingSenderId: '319907892766',
    projectId: 'clueful-e268d',
    authDomain: 'clueful-e268d.firebaseapp.com',
    storageBucket: 'clueful-e268d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZMXDgdj2iXHgo9x2dc8fyYpnjb8nwBRM',
    appId: '1:319907892766:android:6e6a28268fe2a59907680f',
    messagingSenderId: '319907892766',
    projectId: 'clueful-e268d',
    storageBucket: 'clueful-e268d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCti0I7sugZ0hw9VEevtJnDMz372crR3ok',
    appId: '1:319907892766:ios:2d96fe30c24cccff07680f',
    messagingSenderId: '319907892766',
    projectId: 'clueful-e268d',
    storageBucket: 'clueful-e268d.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

}